const SANCTIONED = new Set(["RU", "BY", "IR", "KP"]);

export const COUNTRIES = [
  { code: "AT", name: "Austria", phone: "+43" },
  { code: "BE", name: "Belgium", phone: "+32" },
  { code: "BG", name: "Bulgaria", phone: "+359" },
  { code: "HR", name: "Croatia", phone: "+385" },
  { code: "CY", name: "Cyprus", phone: "+357" },
  { code: "CZ", name: "Czech Republic", phone: "+420" },
  { code: "DK", name: "Denmark", phone: "+45" },
  { code: "EE", name: "Estonia", phone: "+372" },
  { code: "FI", name: "Finland", phone: "+358" },
  { code: "FR", name: "France", phone: "+33" },
  { code: "DE", name: "Germany", phone: "+49" },
  { code: "GR", name: "Greece", phone: "+30" },
  { code: "HU", name: "Hungary", phone: "+36" },
  { code: "IE", name: "Ireland", phone: "+353" },
  { code: "IT", name: "Italy", phone: "+39" },
  { code: "LV", name: "Latvia", phone: "+371" },
  { code: "LT", name: "Lithuania", phone: "+370" },
  { code: "LU", name: "Luxembourg", phone: "+352" },
  { code: "MT", name: "Malta", phone: "+356" },
  { code: "NL", name: "Netherlands", phone: "+31" },
  { code: "PL", name: "Poland", phone: "+48" },
  { code: "PT", name: "Portugal", phone: "+351" },
  { code: "RO", name: "Romania", phone: "+40" },
  { code: "SK", name: "Slovakia", phone: "+421" },
  { code: "SI", name: "Slovenia", phone: "+386" },
  { code: "ES", name: "Spain", phone: "+34" },
  { code: "SE", name: "Sweden", phone: "+46" },
  { code: "GB", name: "United Kingdom", phone: "+44" },
  { code: "NO", name: "Norway", phone: "+47" },
  { code: "CH", name: "Switzerland", phone: "+41" },
  { code: "IS", name: "Iceland", phone: "+354" },
  { code: "UA", name: "Ukraine", phone: "+380" },
  { code: "MD", name: "Moldova", phone: "+373" },
  { code: "GE", name: "Georgia", phone: "+995" },
  { code: "AL", name: "Albania", phone: "+355" },
  { code: "ME", name: "Montenegro", phone: "+382" },
  { code: "MK", name: "North Macedonia", phone: "+389" },
  { code: "RS", name: "Serbia", phone: "+381" },
  { code: "BA", name: "Bosnia and Herzegovina", phone: "+387" },
  { code: "TR", name: "Turkey", phone: "+90" },
  { code: "US", name: "United States", phone: "+1" },
  { code: "CA", name: "Canada", phone: "+1" },
].filter((c) => !SANCTIONED.has(c.code));
